import { Inter } from 'next/font/google'
import './globals.css'
import { Klee_One } from "next/font/google";
const KleeOne = Klee_One({ weight: "600", subsets: ["latin"] });

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={KleeOne.className}>{children}</body>
    </html>
  )
}
